### ISSUE TITLE
make Model macro work without params

### ISSUE THREAD

**Issue by aiomaster** [trailblazer/trailblazer-macro#14]
if you just want do build an empty model you don't need params every time, but the code enforces it.
The model call https://github.com/trailblazer/trailblazer-macro/blob/master/lib/trailblazer/operation/model.rb#L17 assumes that params: key is given.
Please make that key optional (set to {} by default), so that this Create Operation just works even if params key is not given at calltime:
https://github.com/trailblazer/trailblazer-macro/blob/master/test/operation/model_test.rb#L21

**Comment by KamilMilewski** [comment]
fixed in: https://github.com/trailblazer/trailblazer-macro/commit/270f40fa2353313c1c1ea944121cbb1f2d5a640d
