### ISSUE TITLE
Nested eats Activity

### ISSUE THREAD

**Issue by apotonick** [trailblazer/trailblazer-macro#3]
The following code assumes the nested object is an operation, not an activity.

```ruby
Nested( MyActivity )
```

**Comment by yogeshjain999** [comment]
Yeah, why don't we check for all 3 strategies instead ?

**Comment by apotonick** [comment]
Why do we need the check in the first place?

**Comment by yogeshjain999** [comment]
To identify if `callable` is any kind of activity, to identify static/dynamic usage.

**Comment by apotonick** [comment]
Fixed.
