### ISSUE TITLE
When Nested is called multiple time and the Nested operation use Model(), internally model is not replaced

### ISSUE THREAD

**Issue by emaglio** [trailblazer/trailblazer-macro#6]
Hi,
@sean.winner has uncounted an issue when using `Nested` in combination with `Model`. Here an example:
```
  class SongCreate < Trailblazer::Operation
    step Model(Song, :new)
    ....
  end

  class ArtistCreate < Trailblazer::Operation
    step Model(Artist, :new)
    ....
  end

  class SongSpecialCreate < Trailblazer::Operation
    step Nested(ArtistCreate)
    step Nested(SongCreate)
  end
```
So in `SongCreate`, `model` is still `Artist` even though I expect to have `Song`.

Here a PR with an integration test that should pass ones this is fixed/understood: https://github.com/trailblazer/trailblazer-macro/pull/7

Cheers

**Comment by apotonick** [comment]
Ah, sorry, I think I know what the problem is, it's the default injection of `model.class`. I need to think about this, but good timing, as I wanted to improve this anyway! :grimacing:

**Comment by marctich** [comment]
As discussed with @apotonick, we need a scoping feature for this to be fixed properly

**Comment by artur79** [comment]
@emaglio I had a bit similar issue (but not exactly the same, I had combination of Nested macro and magnetic_to param) in my app. Maybe by snippet will help here too:
`
step :create artist

def create_artist(ctx, params:, **)
      ArtistCreate.call(params: params)
end
`

**Comment by emaglio** [comment]
@artur79 thanks for your comment but I don’t think that is a good solution because the 2 operations are not composed using TRB so you will loose all the TRB features like the trace for example (other features are still in dev mode).
So the actual workaround is to set model manually instead of using the Model macro - the bug here comes up when Nested and Model are used multiple times, if you use instead ctx[:model] = Song.new you won’t have any issue

**Comment by claudio** [comment]
We have experienced the same issue just using the Model macro in one step and then Nesting an operation that also uses the Model macro:

`class SongCreate < Trailblazer::Operation
  step Model(Song, :new)
            ....
end

class SongSpecialCreate < Trailblazer::Operation
  step Model(Artist, :new)
  step Nested(SongCreate)
end
`
model is still Artist in this case too.

**Comment by artur79** [comment]
@emaglio when using ctx[:model] = Song.new you are not loosing also TRB trace and stuff as well ?

**Comment by emaglio** [comment]
https://github.com/trailblazer/trailblazer-macro/commit/3f5793423ae1a0777d86d10b07779ea1dbd30997#diff-4211402ec72b93c8b7c712fd7f1b1505R5 fixes this bug - going to merge this https://github.com/trailblazer/trailblazer-macro/pull/7 which tests the bug is fixed
